const products = [
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-pro-max_3.png",
        price: "33,990,000₫",
        category: "Smartphone",
        brand: "Apple",
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/s/ss-s24-ultra-den-600.png",
        price: "29,990,000₫",
        category: "Smartphone",
        brand: "Samsung",
    },
    {
        id: 3,
        name: "MacBook Air M2",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_air_m2_1_1_1.jpg",
        price: "26,990,000₫",
        category: "Laptop",
        brand: "Apple",
    },
    {
        id: 4,
        name: "ASUS ROG Zephyrus G14",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_1__7_45.png",
        price: "39,990,000₫",
        category: "Laptop",
        brand: "ASUS",
    },
    {
        id: 5,
        name: "Dell XPS 15",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/e/text_ng_n_9__1_43.png",
        price: "42,990,000₫",
        category: "Laptop",
        brand: "Dell",
    },
    {
        id: 6,
        name: "Sony WH-1000XM5",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/a/tai-nghe-chup-tai-sony-wh-1000xm5.png",
        price: "8,490,000₫",
        category: "Accessory",
        brand: "Sony",
    },
    {
        id: 7,
        name: "Logitech MX Mechanical",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/b/a/ban-phim-co-khong-daylogitech-mx-mechanical-mini-update.png",
        price: "3,290,000₫",
        category: "Accessory",
        brand: "Logitech",
    },
    {
        id: 8,
        name: "Xiaomi Redmi Note 12",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/t/gtt_7766_3__1_4_2.jpg",
        price: "6,990,000₫",
        category: "Smartphone",
        brand: "Xiaomi",
    },
    {
        id: 9,
        name: "LG UltraFine 5K",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/m/smart-tivi-lg-evo-oled-55g5psa-4k-55-inch-2025.png",
        price: "28,990,000₫",
        category: "Màn Hình",
        brand: "LG",
    },
    {
        id: 10,
        name: "Apple Watch Series 9",
        image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/a/p/apple_lte_3__1.png",
        price: "11,990,000₫",
        category: "Accessory",
        brand: "Apple",
    },
];

export default products;
